version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./sql/initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prest-test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "prest"]
      interval: 30s
      retries: 3
  prest:
    image: prest/prest:latest
    links:
      - "postgres:postgres"
    environment:
      - PREST_PG_HOST=postgres
      - PREST_PG_USER=postgres
      - PREST_PG_PASS=postgres
      - PGPASSWORD=postgres
      - PREST_PG_DATABASE=prest-test
      - PREST_PG_PORT=5432
      - PREST_SSL_MODE=disable
      - BE_CRASHER=1
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
